### PR TITLE
Updated documentation

### PR DESCRIPTION
**Pull request by valentinpolitov**
- Updated missing errors
- Added `Introspection` and `Data Proxy` errors
- Splitted error groups in different files
- Prefixed errors groups names with `Prisma`
- [Re-exported old variables for backward compatibility](https://github.com/vinpac/prisma-error-enum/pull/3/commits/a2af4716318cac1e6a897a2a4198d85c64e335e8)
- [Default export PrismaError](https://github.com/vinpac/prisma-error-enum/pull/3/commits/59ce0ee97e097e003c1e68e32dfc0fc7a18dc7ad)

### CODE REVIEW

**Comment by vinpac** [comment]
Hey @valentinpolitov , I do like and appreciate this, but I'm afraid this imposes breaking changes. Could you please also export the variables names wihtout the Prefix, so it's backward compatible? Thanks!

**Comment by valentinpolitov** [comment]
> Hey @valentinpolitov , I do like and appreciate this, but I'm afraid this imposes breaking changes. Could you please also export the variables names wihtout the Prefix, so it's backward compatible? Thanks!

Hey @vinpac , I've re-exported old variables and marked them with `@deprecated` tag. I believe prefixing variables with `Prisma` will keep code more intuitive.

Release could also be bumped to v0.2.0 so people using this package notice changes

**Comment by valentinpolitov** [comment]
Hey @vinpac did you have a chance to take a look at the changes?

**Comment by valentinpolitov** [comment]
Ping @vinpac

**Pull request merged**
